// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDaNmL9HK1x0jq2YYDgpBEHWCctdaO7Y',
    appId: '1:299269440224:web:192a663846359d5a2d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    authDomain: 'bancolombia-fake.firebaseapp.com',
    databaseURL: 'https://bancolombia-fake-default-rtdb.firebaseio.com',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
    measurementId: 'G-YLWJH0Z2DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwOaML8Tt9AWD_aAcVm6u3LZZ_fmPDaU',
    appId: '1:299269440224:android:fc56337ded446de62d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjZKa94_DhLOCPSd1DAtjY5Wvt4uYV4CI',
    appId: '1:299269440224:ios:a501fe63973fba662d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
    iosBundleId: 'com.example.bancolombia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjZKa94_DhLOCPSd1DAtjY5Wvt4uYV4CI',
    appId: '1:299269440224:ios:a501fe63973fba662d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
    iosBundleId: 'com.example.bancolombia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsDaNmL9HK1x0jq2YYDgpBEHWCctdaO7Y',
    appId: '1:299269440224:web:fba97d7a80283a9d2d8685',
    messagingSenderId: '299269440224',
    projectId: 'bancolombia-fake',
    authDomain: 'bancolombia-fake.firebaseapp.com',
    storageBucket: 'bancolombia-fake.firebasestorage.app',
    measurementId: 'G-711GMLYZ23',
  );
}
