workflows:
  ios-build-test:
    name: iOS Build Test (No Signing)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios 
          rm -rf Podfile.lock
          rm -rf Pods/
          pod install --repo-update
      - name: Flutter analyze
        script: flutter analyze
      - name: Test iOS compilation (no actual build)
        script: |
          flutter build ios --release --no-codesign --debug-info-dir-path=build/ios/dSYMs
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - josueyepez0203@gmail.com
        notify:
          success: true
          failure: true
