workflows:
  android-workflow:
    name: Android Build
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - josueyepez0203@gmail.com
        notify:
          success: true
          failure: true
